title: Hyungcheol Noh's Blog
description: This is my blog page for organizing machine learning studies and personal projects.
show_downloads: false

baseurl: "/blog_temp" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://hcnoh.github.io" # change this to the base hostname & protocol for your site

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Lore Pirri"
image: /thumbnail-jumbo.png
twitter:
  username: lorepirri
#  site:
facebook:
  #publisher: 100002031927279
  profile_id: 100002031927279
  #app_id: 100002031927279
  authors: Hyungcheol Noh
disqus:
  shortname: hcnoh
#  admins:
